name: road-segmentation
channels:
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - matplotlib
  - scipy
  - scikit-image
  - ipywidgets
  - jupyter
  - widgetsnbextension
  - scikit-learn
  - tqdm
